name: Train Model
description: Trains the RNN model.
inputs:
  - {name: model, type: Model}
  - {name: train_loader, type: Dataset}
  - {name: config, type: String}
outputs:
  - {name: trained_model, type: Model}
  - {name: epoch_loss, type: String}
implementation:
  container:
    image: kushagra4761/nesy-factory:t2.6
    command:
      - sh
      - -c
      - |
        exec "$0" "$@"
      - python3
      - -u
      - -c
      - |
        import argparse
        import json
        import os
        import pickle
        import sys
        import torch
        
        from nesy_factory.RNNs.simple_rnn import SimpleRNN
        from nesy_factory.RNNs.gru import GRU

        parser = argparse.ArgumentParser()
        parser.add_argument('--model', type=str, required=True)
        parser.add_argument('--train_loader', type=str, required=True)
        parser.add_argument('--config', type=str, required=True)
        parser.add_argument('--trained_model', type=str, required=True)
        parser.add_argument('--epoch_loss', type=str, required=True)
        args = parser.parse_args()

        config = json.loads(args.config)

        with open(args.model, 'rb') as f:
            model_obj = pickle.load(f)

        with open(args.train_loader, 'rb') as f:
            train_loader_obj = pickle.load(f)

        print("Starting Model Training")
        epoch_loss_data = []
        for epoch in range(config['epochs']):
            model_obj.train()
            total_train_loss = 0
            for inputs, labels in train_loader_obj:
                loss = model_obj.train_step((inputs, labels))
                total_train_loss += loss
            
            avg_train_loss = total_train_loss / len(train_loader_obj)
            print(f"Epoch {epoch+1:02d}/{config['epochs']} | Train Loss: {avg_train_loss:.6f}")
            epoch_loss_data.append({'epoch': epoch, 'loss': avg_train_loss})
        
        output_dir_epoch_loss = os.path.dirname(args.epoch_loss)
        if output_dir_epoch_loss and not os.path.exists(output_dir_epoch_loss):
            os.makedirs(output_dir_epoch_loss, exist_ok=True)
        with open(args.epoch_loss, 'w') as f:
            f.write(json.dumps(epoch_loss_data))
        print("Finished Model Training ")

        os.makedirs(os.path.dirname(args.trained_model), exist_ok=True)
        torch.save(model_obj.state_dict(), args.trained_model)

        print(f"Saved trained model to {args.trained_model}")
    args:
      - --model
      - {inputPath: model}
      - --train_loader
      - {inputPath: train_loader}
      - --config
      - {inputValue: config}
      - --trained_model
      - {outputPath: trained_model}
      - --epoch_loss
      - {outputPath: epoch_loss}
